### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by eirynferguson** [ARK-04/Asena-Assesement-1-OOP#3]
- Your use of comments helped me to understand what was going on throughout your code.
- You have good error handling, ensuring users can correct when they enter an incorrect value.
- I am curious to know why you used multiple testing functions. You have one for each section. Is this easier than only using the one to cover everything?
- In shuffleCardPack, you have used shuffledDeck.Clear(). What does this do within the class?
- Could you explain why you used public enums to set the values within the card class?
- Overall you have a really good code that uses the classes well.

**Comment by ARK-04** [comment]
Thank you for looking at my code for me. In responce to your questions:

- Although it would be useful to have all the input checks in the same place, it is not possible as the program asks the user multiple questions which have to be in different parts of the code. It could potentially be put in a seperate function which could be called from each place its needed but since some of the inputs are called in the classes, it would require calling this function first, returning a bool and then adding a if statement to check the result before calling the class which effectivly makes it needless.
- In shuffleCardPack I created a new deck to hold the new order of cards, the shuffleDeck, and then when the whole deck has moved from the deck list into the shuffleDeck it is copied into the deck as the new order and ending the need of the shuffleDeck in this loop. Since riffle shuffles have to be called multiple times to be effective, the shuffleDeck is cleared at the end of this loop so it can be used again in the next one.
- Using enum to create the cards means that the program can access the value of the suites and numbers while they are stored and displayed to the user as their written versions.
